### ISSUE TITLE
Mac broken with Nix

### ISSUE THREAD

**Issue by wd15** [wd15/pygraspi#10]
Following does not work with Nix on Mac:

    python -c 'import send2trash; print(send2trash.__path__)'

and

    jupyter notebook --no-browser

Can 

```
name: MacOS Bug with Nix
on: [push, pull_request]
jobs:
  pygraspi-nix-test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --command "python -c 'import send2trash; print(send2trash.__path__)'"
      - run: nix-shell --pure --command "jupyter notebook --no-browser"
```
